**1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.**
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]


In [3]:
import numpy as np 
l = [12.23, 13.32, 100, 36.32]
arr= np.array(l)
print("Original List is : ",l)
print("One Daimentinal Array : ",arr)


Original List is :  [12.23, 13.32, 100, 36.32]
One Daimentinal Array :  [ 12.23  13.32 100.    36.32]


**2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:**
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


In [4]:
matrix = np.arange(2,11).reshape(3,3)
# print(np.arange(2,11))
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**3. Write a Python program to create a null vector of size 10 and update sixth value to 11.**
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
null_vector = np.zeros(10)
# print(np.zeros(10))
# print(np.ones(10))
null_vector[5]=11
print(null_vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


**4. Write a Python program to reverse an array (first element becomes last).
Original array:**
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [6]:
original_arr = np.arange(12,38)
reversed_arr = np.flip(original_arr)
print(f"Original Array : {original_arr}")
print(f"reversed Array : {reversed_arr}")

Original Array : [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed Array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:**
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [7]:
original_arr = np.arange(12,38)
reversed_arr = np.flip(original_arr)
print(f"Original Array : {original_arr}")
print(f"reversed Array : {reversed_arr}")

Original Array : [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed Array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [8]:
original_arr = np.ones((5,5))
original_arr[1:-1,1:-1] = 0
print(original_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:**
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [9]:
arr = np.ones((3,3))
arr_with_border = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(arr)
print(arr_with_border)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:**
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]


In [10]:
checkboard = np.zeros((8,8),dtype=int)
checkboard[1::2,::2] = 1
checkboard[::2,1::2] = 1
print(checkboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**8. Write a Python program to convert a list and tuple into arrays.
List to array:**
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]


In [11]:
list_value = [1,2,3,4,5,6,7,8]
tuple_value = ((8,4,6),(1,2,3,))
arr_list = np.array(list_value)
arr_tuple = np.array(tuple_value)
print(arr_list)
print(arr_tuple)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


**9. Write a Python program to append values to the end of an array.
Expected Output:**
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [12]:
arr =np.array( [10,20,30])
values_to_append=np.array([40,50,60,70,80,90])
arr_append = np.append(arr,values_to_append)
print(arr_append)

[10 20 30 40 50 60 70 80 90]


**10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.**
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [13]:
original_arr =np.array([ 1.00000000+0.j, 0.70710678+0.70710678j]) 
real_part = np.real(original_arr)
imaginary_part = np.imag(original_arr)
print(f"Real part of array {real_part}")
print(f"Imaginary Part of array {imaginary_part}")

Real part of array [1.         0.70710678]
Imaginary Part of array [0.         0.70710678]
