**1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.**
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]


In [3]:
import numpy as np 
l = [12.23, 13.32, 100, 36.32]
arr= np.array(l)
print("Original List is : ",l)
print("One Daimentinal Array : ",arr)


Original List is :  [12.23, 13.32, 100, 36.32]
One Daimentinal Array :  [ 12.23  13.32 100.    36.32]


**2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:**
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


In [4]:
matrix = np.arange(2,11).reshape(3,3)
# print(np.arange(2,11))
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**3. Write a Python program to create a null vector of size 10 and update sixth value to 11.**
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
null_vector = np.zeros(10)
# print(np.zeros(10))
# print(np.ones(10))
null_vector[5]=11
print(null_vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


**4. Write a Python program to reverse an array (first element becomes last).
Original array:**
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [6]:
original_arr = np.arange(12,38)
reversed_arr = np.flip(original_arr)
print(f"Original Array : {original_arr}")
print(f"reversed Array : {reversed_arr}")

Original Array : [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed Array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:**
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [7]:
original_arr = np.arange(12,38)
reversed_arr = np.flip(original_arr)
print(f"Original Array : {original_arr}")
print(f"reversed Array : {reversed_arr}")

Original Array : [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed Array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [8]:
original_arr = np.ones((5,5))
original_arr[1:-1,1:-1] = 0
print(original_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:**
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [9]:
arr = np.ones((3,3))
arr_with_border = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(arr)
print(arr_with_border)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:**
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]


In [10]:
checkboard = np.zeros((8,8),dtype=int)
checkboard[1::2,::2] = 1
checkboard[::2,1::2] = 1
print(checkboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**8. Write a Python program to convert a list and tuple into arrays.
List to array:**
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]


In [11]:
list_value = [1,2,3,4,5,6,7,8]
tuple_value = ((8,4,6),(1,2,3,))
arr_list = np.array(list_value)
arr_tuple = np.array(tuple_value)
print(arr_list)
print(arr_tuple)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


**9. Write a Python program to append values to the end of an array.
Expected Output:**
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [12]:
arr =np.array( [10,20,30])
values_to_append=np.array([40,50,60,70,80,90])
arr_append = np.append(arr,values_to_append)
print(arr_append)

[10 20 30 40 50 60 70 80 90]


**10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.**
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [13]:
original_arr =np.array([ 1.00000000+0.j, 0.70710678+0.70710678j]) 
real_part = np.real(original_arr)
imaginary_part = np.imag(original_arr)
print(f"Real part of array {real_part}")
print(f"Imaginary Part of array {imaginary_part}")

Real part of array [1.         0.70710678]
Imaginary Part of array [0.         0.70710678]


**11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.**
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


In [16]:
arr = np.array([1,2,3])
size_of_array = arr.size
bytes_per_element = arr.itemsize
total_bytes = arr.nbytes
print(f"Size of array {size_of_array}")
print(f"Length of one element in bytes : {bytes_per_element}")
print(f"Total Bytes : {total_bytes}")

Size of array 3
Length of one element in bytes : 4
Total Bytes : 12


**12. Write a Python program to find common values between two arrays.
Expected Output:**
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]


In [17]:
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])
common_values = np.intersect1d(arr1,arr2)
print(f"Common values {common_values}")

Common values [10 40]


**13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.**
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [18]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])
set_difference = np.setdiff1d(arr1,arr2) # not present in the second arrays elements of first array 
print(f"Set difference between Array1 and Array2 is {set_difference}")

Set difference between Array1 and Array2 is [1 2 3]


**14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.**
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [21]:
arr1 = np.array([0,10,20,30,40,60,80])
arr2 = np.array([10,30,40,50,70])
set_xor = np.setxor1d(arr1,arr2)
print(f"Unique values that are in only one (not both) of the input arrays : {set_xor}"  )

Unique values that are in only one (not both) of the input arrays : [ 0 20 50 60 70 80]


**15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]**
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [20]:
a = np.array([1,2])
b = np.array([4,5])

comparison_gt = np.greater(a,b)
comparison_gte = np.greater_equal(a,b)
comparison_lt = np.less(a,b)
comparison_lte = np.less_equal(a,b)
print(f"a>b : {comparison_gt}")
print(f"a>=b : {comparison_gte}")
print(f"a<b : {comparison_lt}")
print(f"a<=b : {comparison_lte}")

a>b : [False False]
a>=b : [False False]
a<b : [ True  True]
a<=b : [ True  True]


**15. Write a Python program to save a NumPy array to a text file.**

In [22]:
l = np.arange(1,7).reshape(2,3)
arr = np.array(l)
# save array to text files
np.savetxt('array.txt',arr)
# load array from the text file
load_arr = np.loadtxt('array.txt')
print(f"Original Array : {arr}")
print(f"Loaded array : {load_arr}")

Original Array : [[1 2 3]
 [4 5 6]]
Loaded array : [[1. 2. 3.]
 [4. 5. 6.]]
