**1. Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module.**

In [1]:
import pandas as pd
import numpy as np
# creating 1D array-like object 
l = np.arange(1,6)
series_obj = pd.Series(l)
print(series_obj)

0    1
1    2
2    3
3    4
4    5
dtype: int32


C:\Users\admin\AppData\Local\Temp\ipykernel_9056\2657961247.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


**2. Write a Python program to convert a Panda module Series to Python list and it's type.**

In [3]:
python_list = series_obj.tolist()
print("Python List : ",python_list)
print("Types of teh python list : ",type(python_list))

Python List :  [1, 2, 3, 4, 5]
Types of teh python list :  <class 'list'>


**3. Write a Python program to add, subtract, multiple and divide two Pandas Series.**
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [4]:
series1 = pd.Series(l)
series2 = pd.Series([2,4,6,8,10])
add = series1 + series2
sub = series1 - series2
mul = series1 * series2
div = series1 / series2
print(f"Addition is : {add}")
print(f"Substraction is : {sub}")
print(f"multiplication is : {mul}")
print(f"Division is : {div}")


Addition is : 0     3
1     6
2     9
3    12
4    15
dtype: int64
Substraction is : 0   -1
1   -2
2   -3
3   -4
4   -5
dtype: int64
multiplication is : 0     2
1     8
2    18
3    32
4    50
dtype: int64
Division is : 0    0.5
1    0.5
2    0.5
3    0.5
4    0.5
dtype: float64


**4. Write a Python program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array**
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [5]:
l = np.arange(0,7)
arr = pd.Series(l)
pow = pd.Series(l)

res = arr.apply(lambda x:x ** pow)

print(f"Original array {arr.values}")
print(f"Power  is : {res.values}")


Original array [0 1 2 3 4 5 6]
Power  is : [[    1     0     0     0     0     0     0]
 [    1     1     1     1     1     1     1]
 [    1     2     4     8    16    32    64]
 [    1     3     9    27    81   243   729]
 [    1     4    16    64   256  1024  4096]
 [    1     5    25   125   625  3125 15625]
 [    1     6    36   216  1296  7776 46656]]


**5. Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels.**
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [6]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame from the dictionary
df = pd.DataFrame(exam_data, index=labels)

# Display the DataFrame
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


**6. Write a Python program to display a summary of the basic information about a
specified Data Frame and its data.**
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [7]:
print(df.info)

<bound method DataFrame.info of         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes>


**7. Write a Python program to get the first 3 rows of a given DataFrame.**
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [8]:
df.head(3)

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

**8. Write a Python program to select the 'name' and 'score' columns from the following
DataFrame.**
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [9]:
print(df[['name','score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


**9. Write a Python program to select the specified columns and rows from a given data
frame.**
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [10]:
# columns in the rows
selected_row = df.loc[['b','d','f','g'],['name','score']]
print(selected_row)

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5


**10. Write a Python program to select the rows where the number of attempts in the
examination is greater than 2.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [11]:
# number of attempts greater than 2
selected_row = df[df['attempts'] > 2]
print(selected_row)

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


**11. Write a Python program to count the number of rows and columns of a DataFrame.**
Sample data:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [12]:
num_row = len(df)
num_col = len(df.columns)
print(f"Number of columns : {num_col}")
print(f"Number of Rows : {num_row}")

Number of columns : 4
Number of Rows : 10


**12. Write a Python program to select the rows where the score is missing, i.e. is NaN.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [13]:
# score is NaN then find that 
missing_score = df[df['score'].isna()]
print(missing_score)

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


**13. Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15**

In [14]:
# number of addtmpts is less than 2 and score greater than 15
selected_row = df[(df['attempts'] < 2) & (df['score']>15)]
print(selected_row) 

    name  score  attempts qualify
j  Jonas   19.0         1     yes


**14. Write a Python program to change the score in row 'd' to 11.5.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [15]:
# change the score of d to 11.5
df.loc['d','score'] = 11.5
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


**15. Write a Python program to calculate the sum of the examination attempts by the
students.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [16]:
# calcutation of the sum of the attempts by students
sum_attempts = df['attempts'].sum()
print(sum_attempts)

19


**16. Write a Python program to calculate the mean score for each different student in
DataFrame.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [23]:
# calculate the mean score for each different student in Dataframe 
mean_score = df.groupby('name')['score'].mean()  
print(mean_score)

name
Anastasia    12.5
Dima          9.0
Emily         9.0
James         NaN
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Suresh       15.5
Name: score, dtype: float64


**17. Write a Python program to append a new row 'k' to data frame with given values for
each column. Now delete the new row and return the original DataFrame.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"

In [18]:
import pandas as pd
import numpy as np
18. Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"z
# Given DataFrame
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

# Values for the new row 'k'
new_row_values = {"name": "Suresh", "score": 15.5, "attempts": 1, "qualify": "yes"}

# Append the new row 'k' to the DataFrame
df.loc['k'] = new_row_values

# Print the DataFrame after appending the new row
print("DataFrame after appending new row 'k':")
print(df)

# Delete the new row 'k' and return the original DataFrame
df = df.drop(index='k')

# Print the original DataFrame after deleting the new row 'k'
print("\nOriginal DataFrame after deleting new row 'k':")
print(df)


DataFrame after appending new row 'k':
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

Original DataFrame after deleting new row 'k':
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


**18. Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"

In [20]:
import pandas as pd
import numpy as np

# Given DataFrame
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Values for the new row 'k'
new_row_values = {"name": "Suresh", "score": 15.5, "attempts": 1, "qualify": "yes"}

# Create the DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Append the new row 'k' to the DataFrame
df.loc['k'] = new_row_values

# Sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order
df_sorted = df.sort_values(by=['name', 'score'], ascending=[False, True])

# Print the sorted DataFrame
print("DataFrame sorted by 'name' in descending order, then by 'score' in ascending order:")
print(df_sorted)


DataFrame sorted by 'name' in descending order, then by 'score' in ascending order:
        name  score  attempts qualify
k     Suresh   15.5         1     yes
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes


**19. Write a Python program to replace the 'qualify' column contains the values 'yes' and
'no' with True and False.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [21]:
df['qualify'] = df['qualify'].replace({'yes':True,'no':False})
print(df)

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True
k     Suresh   15.5         1     True


C:\Users\admin\AppData\Local\Temp\ipykernel_9056\1941523847.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['qualify'] = df['qualify'].replace({'yes':True,'no':False})


**20. Write a Python program to delete the 'attempts' column from the DataFrame.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [24]:
df=df.drop('attempts',axis=1)
print(df)

        name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d      James    NaN    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
j      Jonas   19.0     True
k     Suresh   15.5     True


**21. Write a Python program to insert a new column in existing DataFrame.**
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [25]:
# inserting new columns 
df['new_column'] = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J','K']
print(df)

        name  score  qualify new_column
a  Anastasia   12.5     True          A
b       Dima    9.0    False          B
c  Katherine   16.5     True          C
d      James    NaN    False          D
e      Emily    9.0    False          E
f    Michael   20.0     True          F
g    Matthew   14.5     True          G
h      Laura    NaN    False          H
i      Kevin    8.0    False          I
j      Jonas   19.0     True          J
k     Suresh   15.5     True          K


**22. Write a Python program to iterate over rows in a DataFrame**

In [26]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Values for the new row 'k'
new_row_values = {"name": "Suresh", "score": 15.5, "attempts": 1, "qualify": "yes"}

# Create the DataFrame
df = pd.DataFrame(exam_data, index=labels)

for index, row in df.iterrows():
    print(row['name'], row['score'], row['attempts'], row['qualify'])

Anastasia 12.5 1 yes
Dima 9.0 3 no
Katherine 16.5 2 yes
James nan 3 no
Emily 9.0 2 no
Michael 20.0 3 yes
Matthew 14.5 1 yes
Laura nan 1 no
Kevin 8.0 2 no
Jonas 19.0 1 yes


**23. Write a Python program to get list from DataFrame column headers.**
Sample data:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [27]:
col_headers= df.columns.tolist()
print(col_headers)

['name', 'score', 'attempts', 'qualify']
